In [1]:
import numpy as np

# NUMPY 
#Numpy is the pythone laibarary its working with array .its work like as numerical data 
#numpy stands for Numerical
normal array is one dimentional array 

In [2]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
a=[12,13,30]
a

[12, 13, 30]

In [4]:
arr1=np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr2=np.identity(5)
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr3=np.arange(5,16,2)
arr3

array([ 5,  7,  9, 11, 13, 15])

In [8]:
arr4=np.linspace(10,20,10)
arr4

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [9]:
arr5=arr4.copy()
arr5

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [10]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr1.shape

(3, 3)

In [12]:
arr6=np.array([[1,2],[3,4],[5,6],[7,8]])
arr6

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
arr6.shape

(4, 2)

In [14]:
print(type)

<class 'type'>


In [15]:
arr6.ndim

2

In [16]:
print(type(arr6))

<class 'numpy.ndarray'>


In [17]:
arr1.size

9

In [18]:
print(arr6.dtype)

int32


In [19]:
arr1.itemsize

8

In [20]:
b=np.array([10,20.8,45])

In [21]:
arr1.dtype

dtype('float64')

In [22]:
b

array([10. , 20.8, 45. ])

In [23]:
arr1.astype('float')

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
print(b.dtype)

float64


In [25]:
b=np.array([10,"komal",45])
b

array(['10', 'komal', '45'], dtype='<U11')

In [26]:
ab=np.array([[2,3,4],[5,6,7]])
ab

array([[2, 3, 4],
       [5, 6, 7]])

In [27]:
print(ab.dtype)

int32


In [28]:
ab=np.array([[3,4,5,6]])
ab

array([[3, 4, 5, 6]])

In [29]:
print(ab.ndim)

2


In [30]:
ab=np.array(20)
ab
print(ab.ndim)

0


In [31]:
import numpy as np
ab=np.array([5,6,8])
for x in ab:
    print(x)

5
6
8


In [32]:
k=np.array([[[2,3],[3,4],[5,6],[7,8]]])
for x in k:
    print(x)

[[2 3]
 [3 4]
 [5 6]
 [7 8]]


In [33]:
k=np.array([[[2,3],[3,4],[5,6],[7,8]]])
for x in np.nditer(k):
    print(x)

2
3
3
4
5
6
7
8


In [34]:
# array split

In [35]:
import numpy as np
ab=np.array([1,2,3,4,5,6,7,8])
a=np.array_split(ab,2)
a

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [36]:
ab=np.array([1,2,9,3,4,5,6,7,8])
a=np.array_split(ab,2)
a

[array([1, 2, 9, 3, 4]), array([5, 6, 7, 8])]

In [37]:
ab=np.array([1,2,3,4,8,5,6,7,8])
a=np.array_split(ab,4)
a

[array([1, 2, 3]), array([4, 8]), array([5, 6]), array([7, 8])]

In [38]:
print(a[0])

[1 2 3]


In [39]:
print(a[-1])

[7 8]


In [40]:
ab=np.array([1,2,3,4,8,5,6,7,8,12,13,23,45])
a=np.array_split(ab,5)
a

[array([1, 2, 3]),
 array([4, 8, 5]),
 array([6, 7, 8]),
 array([12, 13]),
 array([23, 45])]

In [41]:
print(a[-2])

[12 13]


In [42]:
#Two dimentional array
a=np.array([[1,2,3,4,5],[6,7,8,9,4,6]])
ab=np.array_split(a,4)
ab


C:\Users\Admin\AppData\Local\Temp/ipykernel_13216/414445869.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[1,2,3,4,5],[6,7,8,9,4,6]])


[array([list([1, 2, 3, 4, 5])], dtype=object),
 array([list([6, 7, 8, 9, 4, 6])], dtype=object),
 array([], dtype=object),
 array([], dtype=object)]

In [43]:
a=np.array([1,2,3,4,5])
b=np.array([2,3,4,5,6])
c=np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [44]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[2,3,4,5,6],[1,2,3,4,5]])
c=np.concatenate((a,b))
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [46]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[2,3,4,5,6],[1,2,3,4,5]])
c=np.concatenate((a,b))
print(a+b)

[[ 3  5  7  9 11]
 [ 2  4  6  8 10]]


In [47]:
#sort
# by asending order

a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
ab=np.sort(a)
ab




array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [48]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
ab=-np.sort(-a)
ab


array([[5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1]])

In [49]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
ab=np.sort(a)[::-1]
ab


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [50]:
# sorting by array multiple time
ab=np.sort(-a)
ab

array([[-5, -4, -3, -2, -1],
       [-5, -4, -3, -2, -1]])

In [51]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
ab=np.flip(a)
ab


array([[5, 4, 3, 2, 1],
       [5, 4, 3, 2, 1]])

In [52]:
# How to serching array
a=np.array([2,3,4,5,6,7,8,9])
ab=np.where(a==2)
print(ab)

(array([0], dtype=int64),)


In [53]:
a=np.array([2,3,4,5,6])
ab=[True,False,True,True,False]
ab=a[ab]
print(ab)


[2 4 5]


In [54]:
arr6=np.arange(24)
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
arr6=np.arange(24).reshape(6,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [56]:
x=np.linspace(-40,40,100)

In [57]:
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [58]:
x.size

100

In [59]:
y=np.sin(x)

In [60]:
y.size

100

In [61]:
a = np.array([1,2,3,4,5,6,8,6,2])

In [62]:
type(a)

numpy.ndarray

In [63]:
a.ndim

1

In [64]:
a.shape

(9,)

In [65]:
a.dtype

dtype('int32')

In [66]:
len(a)

9